spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://43.138.71.234:3306/Mymall_ums?characterEncoding=utf8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 03d1ec9b-9e58-432f-aa10-ff7807e1306c
server:
  port: 8001