spring:
  application:
    name: coupon
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/Mymall_sms
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  #自增主键
server:
  port: 7000