spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/Mymall_pms?characterEncoding=utf8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111
        namespace: 03d1ec9b-9e58-432f-aa10-ff7807e1306c
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false

server:
  port: 10001


